# Generated by Django 4.1.2 on 2022-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
    ]
